import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ImagePlus, LogOut, PenLine, ShieldCheck } from 'lucide-react';
import { isSupabaseConfigured } from '../../lib/blog';
import { createServerSupabaseClient, isStudioAdmin } from '../../lib/supabase/server';
import { requestMagicLink, savePost, signOutStudio } from './actions';

type StudioPageProps = { searchParams: Promise<{ error?: string; sent?: string; success?: string }> };

export default async function StudioPage({ searchParams }: StudioPageProps) {
  const params = await searchParams;
  if (!isSupabaseConfigured) notFound();
  const supabase = await createServerSupabaseClient();
  const { data: { user } } = await supabase!.auth.getUser();
  if (!user || !isStudioAdmin(user.email)) return <main className="studio-shell"><Link href="/" className="studio-back">← Danish Khan</Link><section className="studio-login"><ShieldCheck size={24}/><span className="blog-kicker">Private Studio</span><h1>Write without touching code.</h1><p>Sign in with your approved email to create drafts and publish posts.</p>{params.error === 'denied' && <p className="studio-error" role="alert">This email is not approved for the Studio.</p>}{params.sent && <p className="studio-success" role="status">Check your inbox for the secure sign-in link.</p>}<form action={requestMagicLink}><label htmlFor="studio-email">Your email</label><input id="studio-email" name="email" type="email" autoComplete="email" required placeholder="dk557876@gmail.com"/><button type="submit">Send secure sign-in link</button></form></section></main>;
  return <main className="studio-shell"><header className="studio-header"><div><Link href="/" className="studio-back">← Danish Khan</Link><h1>Studio</h1><p>Draft first. Publish when it is ready.</p></div><form action={signOutStudio}><button className="studio-signout" type="submit"><LogOut size={15}/> Sign out</button></form></header>{params.success && <p className="studio-success" role="status">Post saved. Your public blog is updated if you chose Publish.</p>}<form className="studio-editor" action={savePost}><div className="studio-editor-heading"><div><PenLine size={18}/><h2>New field note</h2></div><div className="studio-actions"><button name="intent" value="draft" type="submit">Save draft</button><button name="intent" value="publish" type="submit" className="studio-publish">Publish</button></div></div><div className="studio-grid"><label>Title<input name="title" required placeholder="A clear, useful article title"/></label><label>URL slug<input name="slug" placeholder="created-from-title-if-empty"/></label></div><label>Short description<textarea name="excerpt" required rows={3} placeholder="The sentence people see before they open the article."/></label><div className="studio-grid"><label>Category<input name="category" defaultValue="Field note"/></label><label>Tags<input name="tags" placeholder="product, growth, founder"/></label></div><fieldset className="studio-cover"><legend><ImagePlus size={16}/> Cover image</legend><label>Upload image<input name="cover_file" type="file" accept="image/png,image/jpeg,image/webp"/></label><span>or</span><label>Image URL<input name="cover_image_url" type="url" placeholder="https://…"/></label></fieldset><label>Article <span>Markdown is supported</span><textarea name="content_md" required rows={18} placeholder={'## Your opening\n\nWrite the first paragraph here…\n\n## A useful section\n\nContinue the story with clear details.'}/></label><details className="studio-seo"><summary>SEO settings</summary><div className="studio-grid"><label>SEO title<input name="seo_title" placeholder="Optional: defaults to article title"/></label><label>SEO description<input name="seo_description" placeholder="Optional: defaults to short description"/></label></div></details><label className="studio-featured"><input name="is_featured" type="checkbox"/> Feature this post at the top of the blog</label><div className="studio-actions studio-actions-bottom"><button name="intent" value="draft" type="submit">Save draft</button><button name="intent" value="publish" type="submit" className="studio-publish">Publish now</button></div></form></main>;
}
