'use client';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { ArrowUpRight, BadgeCheck, CalendarDays, ChevronDown, Github, Linkedin, Mail, Moon, Play, Video } from 'lucide-react';
import Lenis from 'lenis';

const experience=[
 {company:'Siela',role:'Founder',date:'January 2026 — Present',logo:'/portfolio/siela-icon.png',links:[{label:'Visit Siela',url:'https://siela.in/'}],items:['Building an AI-native workspace where an agent handles CRM updates, task management, meetings, reminders, calendar actions and GitHub reporting.','Won the first 10 users within two weeks of launching Siela.']},
 {company:'Grow Legal Research Labs',role:'Co-Founder',location:'SF · Remote',date:'May 2026 — Present',logo:'/portfolio/growlegal.png',links:[{label:'Visit Grow Legal',url:'https://growlegal.ai/'}],items:['Building AI software for immigration and legal workflows.','Working across product research, workflow design, customer discovery, partnerships and founder-led sales.']},
 {company:'OpenSphere.ai + LegalBridge',role:'Growth & Marketing Associate',location:'SF · Remote',date:'September 2024 — April 2026',logo:'/portfolio/opensphere.png',links:[{label:'Visit OpenSphere',url:'https://opensphere.ai/'},{label:'Visit LegalBridge',url:'https://legalbridge.ai/'}],items:['Built and launched the OpenSphere Framer website, contributing to 30,000+ new users and 16,000 active users in roughly four months.','Built a 20,000-prospect pipeline and ran outreach reaching about 40,000 contacts.','Drove growth for sister company LegalBridge and worked on smart questionnaires that collect applicant information for immigration forms and case workflows.']},
 {company:'Deskera',role:'Video Editor · Marketing Team',location:'Singapore · Remote',date:'February 2024 — August 2024',logo:'/portfolio/deskera.png',links:[{label:'Visit Deskera',url:'https://www.deskera.com/'}],items:['Edited marketing and product videos for digital campaigns alongside the marketing and design teams.','Optimised creative for social platforms and ongoing brand initiatives.']},
 {company:'Kontent Media',role:'Video Editor & Graphic Designer · Freelance',date:'September 2022 — January 2024',logo:'/portfolio/kontent-media.png',links:[],items:["Created video edits and graphic design assets for multiple founders and creators through one of India's leading content agencies.",'Worked across content for prominent trading and finance brands, technology creators and chartered accountants.','Handled post-production while also gaining hands-on experience shooting videos and producing content for my own channels.']},
];
const skills=['AI-Native Product Building','Agentic Workflows','SaaS Product Strategy','CRM Systems','Immigration Technology','Product-Led Growth','Go-to-Market Strategy','Early User Acquisition','Founder-Led Sales','Lead Generation & Outreach','Product Marketing','Customer Discovery','Workflow Automation','Framer Web Design','Content Strategy','Video Editing & Post-Production','Video Shooting','Graphic Design','Premiere Pro','After Effects'];
const earlyVideos=[
 {title:'Motion Graphics Magic',url:'https://www.youtube.com/shorts/plrndoYBQfc'},
 {title:'The Future of Meme-Making: The AI Meme Machine',url:'https://www.youtube.com/shorts/jF1c7EVvc2c'},
 {title:'Rare and Useful Websites Every Student Needs',url:'https://www.youtube.com/watch?v=Ctrbne1zxy4'},
 {title:'Avoid These 5 Common Video-Editing Mistakes',url:'https://www.youtube.com/shorts/viEvdcTuhMI'},
 {title:'Why EdTech Startups Are Failing in India',url:'https://www.youtube.com/watch?v=0EK192hVfjE'},
];

function SmoothScroll(){useEffect(()=>{const lenis=new Lenis({autoRaf:true,smoothWheel:true,lerp:.065,wheelMultiplier:1.35,touchMultiplier:1.45,anchors:{offset:-20}});return()=>lenis.destroy()},[]);return null}
function Clock(){const [t,setT]=useState('--:--:--');useEffect(()=>{const f=()=>setT(new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Kolkata',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date()));f();const id=setInterval(f,1000);return()=>clearInterval(id)},[]);return <span>{t}</span>}
function ExperienceCard({item,index}:{item:typeof experience[number],index:number}){const [open,setOpen]=useState(index===0);return <motion.article layout className="experience-card"><button onClick={()=>setOpen(v=>!v)} aria-expanded={open}><span className="company-logo"><Image src={item.logo} alt={`${item.company} logo`} width={42} height={42}/></span><span className="company-copy"><strong>{item.company}</strong><span className="role-row"><small>{item.role}</small>{'location' in item&&<em>{item.location}</em>}</span></span><time>{item.date}</time><motion.span animate={{rotate:open?180:0}}><ChevronDown size={16}/></motion.span></button><AnimatePresence initial={false}>{open&&<motion.div initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}} className="experience-details"><ul>{item.items.map(x=><li key={x}>{x}</li>)}</ul><div className="experience-links">{item.links.map(link=><a className="experience-link" href={link.url} target="_blank" rel="noreferrer" key={link.url}>{link.label} <ArrowUpRight size={13}/></a>)}</div></motion.div>}</AnimatePresence></motion.article>}
function Dock(){const [light,setLight]=useState(false);useEffect(()=>{document.documentElement.dataset.theme=light?'light':''},[light]);return <nav className="dock" aria-label="Quick links"><a href="#top" className="dock-avatar"><Image src="/portfolio/danish-pfp.png" alt="Danish Khan illustrated avatar" width={32} height={32}/></a><span/><a href="https://github.com/danishdotdev" target="_blank" aria-label="GitHub"><Github size={18}/></a><span/><a href="https://www.linkedin.com/in/danishkhan-in/" target="_blank" aria-label="LinkedIn"><Linkedin size={18}/></a><span/><a href="https://x.com/danishdotdev" target="_blank" aria-label="X"><b className="x-icon">𝕏</b></a><span/><a href="mailto:dk557876@gmail.com" aria-label="Email"><Mail size={18}/></a><span/><button type="button" onClick={()=>setLight(v=>!v)} aria-label={light?'Switch to dark mode':'Switch to light mode'}><Moon size={18}/></button></nav>}
export default function Home(){return <><SmoothScroll/><div id="top" className="portfolio-panel"><section className="profile"><div className="profile-top"><span>Hola ! I&apos;m</span><Clock/></div><div className="profile-title"><div className="avatar"><Image src="/portfolio/danish-pfp.png" alt="Danish Khan illustrated avatar" width={78} height={78} priority/></div><div><h1>Danish Khan</h1></div></div><p className="identity-line">Founder <i/> Growth Operator <i/> from Kolkata, India.</p><div className="social-row"><a className="resume" href="mailto:dk557876@gmail.com">Contact me</a><a href="mailto:dk557876@gmail.com" aria-label="Email"><Mail size={18}/></a><a href="https://github.com/danishdotdev" target="_blank" aria-label="GitHub"><Github size={18}/></a><a href="https://www.linkedin.com/in/danishkhan-in/" target="_blank" aria-label="LinkedIn"><Linkedin size={18}/></a><a href="https://x.com/danishdotdev" target="_blank" aria-label="X"><b className="x-icon">𝕏</b></a></div><p className="tldr"><b>TL;DR:</b> I started by editing stories people watched. Now I build AI-native products, growth systems and the engines that turn early ideas into momentum.</p></section>
<section id="experience" className="content-section"><h2>Experience</h2><div className="experience-list">{experience.map((x,i)=><ExperienceCard key={x.company} item={x} index={i}/>)}</div></section>
<section id="projects" className="content-section"><h2>Proof of Work</h2><article className="project-card"><div className="project-visual siela-visual simple-siela-visual"><div className="siela-mark"><Image src="/portfolio/siela-icon.png" alt="Siela logo" width={30} height={30}/><span>SIELA · AI-NATIVE WORKSPACE</span></div><strong>One workspace.<br/>One shared context.</strong></div><div className="project-body"><div className="project-heading"><span className="project-name"><Image src="/portfolio/siela-icon.png" alt="Siela logo" width={34} height={34}/><strong>Siela — AI-native workspace</strong></span><div><a href="https://siela.in/" target="_blank">live preview ↗</a></div></div><p className="project-description">An AI-native workspace where an agent handles CRM updates and task management while meetings, calendar, reminders and GitHub reporting stay connected in one operational home. The first 10 users joined within two weeks of launch.</p><div className="chips"><span>AI Agent</span><span>CRM</span><span>Tasks</span><span>Meetings</span><span>Calendar</span></div></div></article>
<article className="project-card"><div className="project-visual gcg-visual"><div className="gcg-mark"><BadgeCheck/><span>GREEN CARD GUIDE AI</span></div><strong>Talent gets you noticed.<br/>Evidence gets you approved.</strong></div><div className="project-body"><div className="project-heading"><strong>Green Card Guide AI</strong><div><a href="https://greencardguide.ai/" target="_blank">live preview ↗</a></div></div><p className="project-description">An AI evidence engine that reads a resume, maps it to extraordinary-ability visa criteria, identifies profile gaps and surfaces relevant judging, speaking, press and award opportunities.</p><div className="chips"><span>AI</span><span>Immigration</span><span>Evidence</span><span>Opportunity Matching</span></div></div></article>
<article className="project-card"><div className="project-visual creative-visual"><div className="views"><Video/><strong>30M+</strong><span>views generated through creative work</span></div></div><div className="project-body"><div className="project-heading"><strong>Freelance creative work</strong><span className="muted-link"><Play size={14}/> editing + shooting</span></div><p className="project-description">Worked with one of India&apos;s largest content agencies and supported creators, finance brands, technology creators and chartered accountants across short-form, long-form and campaign content. My experience includes editing, shooting videos and producing videos for my own channels.</p><div className="early-work"><strong>Early days</strong><p>I started by making videos for myself, then used that work to pitch founders and creators. Those early videos helped me earn the opportunity to manage content for a founder&apos;s account.</p><ol>{earlyVideos.map(video=><li key={video.url}><a href={video.url} target="_blank" rel="noreferrer">{video.title} <ArrowUpRight size={13}/></a></li>)}</ol></div><div className="chips"><span>Premiere Pro</span><span>After Effects</span><span>Video Shooting</span><span>Social</span><span>Storytelling</span></div></div></article></section>
<section className="content-section"><h2>Skills</h2><div className="chips skill-cloud">{skills.map(x=><span key={x}>{x}</span>)}</div></section>
<section id="github" className="content-section"><div className="section-heading"><h2>GitHub</h2><a href="https://github.com/danishdotdev" target="_blank">view profile <ArrowUpRight size={15}/></a></div><div className="github-console"><div className="console-bar"><span><i/><i/><i/></span><code>danishdotdev — contributions</code><Github size={16}/></div><Image src="/portfolio/github-contributions.png" alt="Danish Khan GitHub contribution graph showing 1,283 contributions in the last year" width={886} height={237}/></div></section>
<section id="achievements" className="content-section"><h2>Achievements</h2><article className="achievement-card"><span className="achievement-rank">01</span><div><div className="achievement-heading"><strong>1st Runner Up — Google Prompt War</strong><a href="https://github.com/danishdotdev/smriti" target="_blank" rel="noreferrer">Smriti on GitHub <ArrowUpRight size={13}/></a></div><p>Built Smriti, a voice-first companion that helps students manage their mental well-being during high-stakes exams and result seasons.</p></div></article></section>
<section className="content-section"><h2>Education</h2><article className="education-card"><div><strong>Taradevi Harakhchand Kankaria Jain College</strong><p>BBA — Marketing</p></div><span>2022 — 2025</span></article></section>
<section id="contact" className="contact-card"><h2>Still reading? That means something clicked.<br/>Let&apos;s talk.</h2><a href="mailto:dk557876@gmail.com"><Mail size={17}/> email me</a><a href="https://siela.in/" target="_blank"><CalendarDays size={17}/> see what I&apos;m building</a></section><Dock/></div></>}
